using UnityEngine;

namespace OSMImporter.Traffic.Rules
{
    /// <summary>
    /// DrivingDesire — Struct containing vehicle intents generated by various rules.
    /// </summary>
    public struct DrivingDesire
    {
        public string Source;

        public float TargetSpeed;
        public float TargetLateralOffset;
        public float AccelerationIntent;
        public float BrakeIntent;
        public float SteerIntent;

        public float Risk;
        public float Urgency;
        public float LegalityPenalty;
        public float SocialPressure;

        public static DrivingDesire CreateDefault(string source)
        {
            return new DrivingDesire
            {
                Source = source,
                TargetSpeed = -1f,               // -1 means no speed desire
                TargetLateralOffset = float.NaN, // NaN means no lateral offset desire
                AccelerationIntent = 0f,
                BrakeIntent = 0f,
                SteerIntent = 0f,
                Risk = 0f,
                Urgency = 0f,
                LegalityPenalty = 0f,
                SocialPressure = 0f
            };
        }
    }
}
